#ifndef CSTL_TEMPLATE_H
#define CSTL_TEMPLATE_H

#include <cstl/pproc.h>

#define CSTL__TEMPLATE_PREF CSTL_TMPL
#define CSTL__TEMPLATE_SEP $
#define CSTL__TEMPLATE_BEG_TYPENAMES ST
#define CSTL__TEMPLATE_END_TYPENAMES ET

#define CSTL__MANGLE_TYPES1(t1) t1
#define CSTL__MANGLE_TYPES2(t1, t2) CSTL_CONCAT(t1, CSTL__TEMPLATE_SEP, t2)

#define CSTL__MANGLE_TYPES3(t1, ...) \
    CSTL_CONCAT(t1, CSTL_TEMPLATE__SEP, CSTL__MANGLE_TYPES2(__VA_ARGS__))

#define CSTL__MANGLE_TYPES4(t1, ...) \
    CSTL_CONCAT(t1, CSTL_TEMPLATE__SEP, CSTL__MANGLE_TYPES3(__VA_ARGS__))

#define CSTL__MANGLE_TYPES5(t1, ...) \
    CSTL_CONCAT(t1, CSTL_TEMPLATE__SEP, CSTL__MANGLE_TYPES4(__VA_ARGS__))

#define CSTL__MANGLE_TYPES(...) \
    CSTL__CONCAT2(CSTL__MANGLE_TYPES, CSTL_COUNT(__VA_ARGS__))(__VA_ARGS__)

#define CSTL__MANGLE(basename, ...) \
    CSTL_CONCAT( \
        CSTL__TEMPLATE_PREF, \
        CSTL__TEMPLATE_SEP, \
        basename, \
        CSTL__TEMPLATE_SEP, \
        CSTL__TEMPLATE_BEG_TYPENAMES, \
        CSTL__TEMPLATE_SEP, \
        CSTL__MANGLE_TYPES(__VA_ARGS__), \
        CSTL__TEMPLATE_SEP, \
        CSTL__TEMPLATE_END_TYPENAMES \
    )

#endif /* CSTL_TEMPLATE_H */
